# Generated by Django 3.2 on 2022-07-03 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='personaldata',
            managers=[
            ],
        ),
    ]
